## Homework 2

Please import the following package.

In [1]:
import numpy as np

### Loops

**_How to work with multiple indices?_**

<ol>
    <li> 
        
Use the code from Homework 1 Question 1 to write a function `flatten` that takes as input an array with shape `(r,c)` and outputs an array with shape `(rc,)`.  For example, input `np.array([[1,2], [3,4]])` would yield output `np.array([1,2,3,4])`. Note that the array has two indices. The indices indicate the row and column. We flatten the array by going across the columns in each row. 
    </li>

In [7]:
# Implement this
def flatten(arr):
    '''
    
    function takes as input an array with shape (r,c) and outputs an array with shape (rc,)
    
    arr: array with shape (r,c)
    
    '''
    # flatten each element in 2d array
    temp=[]
    for row in arr:
        
        if type(row) is np.ndarray:
            for item in row:
                temp.append(item)
        else:
            raise NotImplementedError("An error occurred. Is your input an array?")
    return np.array(temp)

    

In [8]:
# test function flatten_v1: 
flatten(np.array([[1,2], [3,4]]))

array([1, 2, 3, 4])

<ol start=2>
<img src="diagram.png" alt="drawing" width="200" style="float:right"/>

<br>
<br>


<li> Modify the function from Question 1. 
 <ul> 
     <li> 
         
Add a parameter called `major`. 
     </li> 
 <li> 
     
Make the default value of `major` be `"row"`
 </li>
 <li> Rewrite the loop so 
      <ul> 
          <li>
              
If `major` is `"row"`, then the array is flattened in row major order
          </li>
      <li> 
      
If `major` is `"column"`, then the array is flattened in column major order 
      </li>
     </ul>
</li>
</ul>
</li>

</ol>

In [4]:
# Implement this, including modifying arguments
def flatten_v2(arr, major='row'):
    '''
    function takes as input an array with shape (r,c) and outputs an array with row-oriented shape (1, rc) by default or column-oriented (rc, 1) if specified 
    
    arr : input a numpy array with shape (r,c)
    major : input desired orientation, row by default (rc,) ; define as column for shape (1,rc)
    '''
        
    # flatten each element in 2d array
    temp=[]
    if major == "row":
        return flatten(arr)
    
    elif major == "col":
        
    
    
                
    return np.array(temp)

    raise NotImplementedError("An error occurred. Is your input an array?")

In [5]:
# test function flatten_v2: 
print(flatten_v2(np.array([[1,2], [3,4]])))
print(flatten_v2(np.array([[1,2], [3,4]]), major='column'))

[1 2 3 4]
[1 3 2 4]


<ol start=3>

<li> 
    
Modify the function from Question 1 to allow for more than two indices. For example, if the input is an array with shape `(r,c,h)` then the output is an array with shape `(rch,)`. So input `np.array([ [[1,2], [3,4]], [[5,6], [7,8]] ])` which has shape `(2,2,2)` would yield output `np.array([1,2,3,4,5,6,7,8])` which has shape `(8,)`. You should approach the problem using recursion.  
</li>

</ol>

In [6]:
# Implement this

def flatten_v3(arr):
    '''
    function takes as input an array with shape (r,c,h) and outputs an array with row-oriented shape (rch,)
    
    arr: input array with n dimensions
    '''
    
    #stop
    if len(arr.shape)==1:
        return arr
    
    #for each item add to a new list and output as array 
    new_arr=[]
    for item in arr:
        new_arr.extend(flatten_v3(item))
    return np.array(new_arr)

    raise NotImplementedError("An error occurred. Is your input an array that can be flattened?")

In [7]:
# test function flatten_v3: 
print(flatten_v3(np.array([[1,2], [3,4]])))
print(flatten_v3(np.array([ [[1,2], [3,4]], [[5,6], [7,8]] ])))

[1 2 3 4]
[1 2 3 4 5 6 7 8]


### Storage

**_How to compress an array with lots of zeros_**

<ol>
<li>
Write a function called `dense_to_sparse` that inputs an array and outputs a dictionary with 
    <ul>
<li>
Keys as tuples containing `(row,column)` of all non-zero entries    
</li>
<li>
Values as the corresponding non-zero entries.
</li>
</ul>

The resulting entries should be in <i>row-major</i> order.

For example, if the input is `np.array([[1,0], [0,4]])` then the output is `{(0,0):1, (1,1):4}`       
</li>
</ol>
    

In [8]:
def dense_to_sparse(arr):
    '''
    function takes as input a sparse array and outputs a dictionary with locations of non-zero entries as keys and their numeric value as values
    
    arr: sparse array input
    '''
    
    # calc shape of input array
    row, col = arr.shape
    
    # initiate dictionary
    dicts={}

    # assign position tuples as keys and value as value
    for i in range(row):
        for j in range(col):
            if arr[i,j] != 0:
                dicts.update({(i, j):arr[i,j]})
        
    return dicts
    
    raise NotImplementedError("An error occurred. Is your input an array with the specified shape?")

In [9]:
#test the function dense_to_sparse
dense_to_sparse(np.array([[1,0], [0,4]]))

{(0, 0): 1, (1, 1): 4}

<ol start=2>
<li>
    
Write an inverse function called `sparse_to_dense`
</li>
</ol>

In [10]:
# Implement this
def sparse_to_dense(d):
    '''
    
    function takes as input a a dictionary with locations of non-zero entries as keys and their numeric value as values and outputs a sparse array
    
    d: dictionary input with tuple positions (r,c) as keys and value as value
    
    '''
    
    # Build an array with zeros of max row, col based on dictionary tuples
    max_row = 0
    max_col = 0
    for (r,c) in d:
        if r > max_row:
            max_row=r
        if c > max_col:
            max_col=c
    new_arr = np.zeros((max_row+1,max_col+1))
    
    # assign a value in position based on the dictionary tuples
    for (i,j) in d:
            new_arr[i][j] = d[(i,j)]
    
    return new_arr
    
    raise NotImplementedError("An error occurred. Is your input a dictionary with the specified shape?")

In [11]:
#test the function sparse_to_dense
sparse_to_dense({(0, 0): 1, (1, 1): 4})

array([[1., 0.],
       [0., 4.]])